---- Base app schema

-- Authors
CREATE TABLE "authors" (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
	name varchar(128) NOT NULL,
	email varchar(128) NOT NULL UNIQUE,

	-- Auth
	password varchar(256) NOT NULL,
	password_salt uuid NOT NULL DEFAULT gen_random_uuid(),
	token_salt uuid NOT NULL DEFAULT gen_random_uuid()
);

-- Posts
CREATE TABLE "posts" (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
	title varchar(256) NOT NULL,
	content varchar(512) NOT NULL,
	author_id BIGINT,
	FOREIGN KEY (author_id) REFERENCES authors(id) ON DELETE SET NULL
);

-- Edit Status
CREATE TYPE EDIT_STATUS AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED');

-- Edits
CREATE TABLE "edits" (
	post_id BIGINT NOT NULL,
	author_id BIGINT NOT NULL,
	status EDIT_STATUS NOT NULL DEFAULT 'PENDING'::EDIT_STATUS,
	new_content text NOT NULL,
	FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE SET NULL,
	FOREIGN KEY (author_id) REFERENCES authors(id) ON DELETE SET NULL,
	PRIMARY KEY (author_id, post_id)
);